### ISSUE TITLE
Permission denied on cpu script execution

### ISSUE THREAD

**Issue by ArtemChandragupta** [0thElement/nixconf#1]
Hi. I am messing around with ags trying to rewrite my waybar with it as a starting point. I tried to copy your cpu script, but I get this error:

```
(com.github.Aylur.ags:892127): Gjs-WARNING **: 00:49:33.531: JS ERROR: GLib.SpawnError: Failed to execute child process “/home/artem/.config/ags/bar/modules/cpu/cpu.sh” (Permission denied)
proc@resource:///com/github/Aylur/ags/utils/exec.js:11:27
execAsync@resource:///com/github/Aylur/ags/utils/exec.js:77:19
startPoll/this._interval<@resource:///com/github/Aylur/ags/variable.js:40:60
interval@resource:///com/github/Aylur/ags/utils/timeout.js:3:5
startPoll@resource:///com/github/Aylur/ags/variable.js:40:30
Variable@resource:///com/github/Aylur/ags/variable.js:26:18
default@resource:///com/github/Aylur/ags/variable.js:130:36
@file:///home/artem/.config/ags/bar/modules/cpu/main.js:1:21
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

Have you encountered this? Do you know how to deal with it? I also use NixOS

Also if I add `#!/usr/bin/env bash`, nothing changes.

**Comment by 0thElement** [comment]
That's something I missed, you should be able to add an `home.file.".config/ags/cpu.sh".executable = true;` (maybe you'll have to do the same for other shell scripts in there too). I manually chmod-ed the shell scripts on my end and it seems GitHub can't preserve the flag

**Comment by ArtemChandragupta** [comment]
Sorry for late respond, I waited [this issue](https://github.com/NixOS/nixpkgs/issues/326278) to be resolved and I can make a rebuild.

Unfortunately, setting only `home.file.".config/ags/bar/modules/cpu/cpu.sh".executable = true;` is not enough, home manager deletes it's link to other ags config for some reason . After realizing this I tried to do `home.file.".config/ags/bar/modules/cpu/cpu.sh".text = builtins.readFile ( ./bar/modules/cpu/cpu.sh )` which resulted in build error.

After that I looked to your config:
```
 home.file =
    let wal = config.wal.enable; in 
    lib.mkMerge [
      {
        ".config/ags/config.js".source = ./config/config.js;
        ".config/ags/wallpapers.js".source = ./config/wallpapers.js;
        ".config/ags/style.css".source = ./config/style.css;
        ".config/ags/cpu.sh".source = ./config/cpu.sh;
        ".config/ags/mem.sh".source = ./config/mem.sh;
        ".config/ags/colors_default.css".source = ./config/colors_default.css;
      }
      (if wal then {
        ".config/wpg/templates/ags.css.base".source = ./config/colors_wal.css;
        ".config/ags/colors.css".source =
          config.lib.file.mkOutOfStoreSymlink
          "/home/zeroth/.config/wpg/templates/ags.css";
      }
      else {
        ".config/hypr/colors.css".source = ./config/colors_default.css;
      })
  ];
```
I am not sure what this is needed for. How home.file."...".text = builtins.readFile differs from home.file."...".source? Why do you need mkMerge and this code in general?

Btw I tried to do this:
```
home.file = lib.mkMerge [
  {
    ".config/ags/bar/modules/cpu/cpu.sh" = {
      executable = true;
      #text = builtins.readFile ( ./config/bar/modules/cpu/cpu.sh );
      source = ./config/bar/modules/cpu/cpu.sh;
    };
  }
];
```
which resulted in `mv: cannot move '/home/artem/.config/ags/bar/modules/cpu/cpu.sh' to '/home/artem/.config/ags/bar/modules/cpu/cpu.sh.hm-backuping': Read-only file system`

**Comment by ArtemChandragupta** [comment]
For some reason, this code works without chmod:
```
const getUsage = Variable("", {
	poll: [
		5000,
		`bash -c "top -b -n 1 | grep 'Cpu(s)' | awk '{print $2}'"`,
		(out) => parseFloat(out).toFixed(0),
	],
});
```

**Comment by ArtemChandragupta** [comment]
So, the answer is to add 'bash' and '-c' to the script as example shows. At least, This works for all my scripts
