### ISSUE TITLE
OpenWallpaper not working

### ISSUE THREAD

**Issue by veri-tty** [0thElement/nixconf#2]
Hi, i love the design of your wallpaper switcher, so ive deployed your flake to try it out, all but the AGS button that calls OpenWallpaper (wifi and bluetooth right above respond, just no reaction from the star button) appears to work and looks great :)
I set a wallpaper directly with swww, hoping to thus trigger the theming functions and error messages as seen in the below screenshot, but that didnt work.
I dont have much of a clue regarding js, so i really dont know how to troubleshoot this.
I have increased the Hyprland resoltution to 2556x1504 (surface laptop 3), might that be the reason?
![swappy-20241008_154740](https://github.com/user-attachments/assets/eefca8bd-a5d9-4995-8035-9524a24f7fe4)

**Comment by 0thElement** [comment]
I'm actually not currently using NixOS on my device right now (since I switched to a new laptop and don't have the disk space to dual boot yet), so I might not be able to provide very helpful advices. Sorry in advance!

I don't think the error is related to AGS, but the colors.conf is missing for hyprland to work properly. Maybe you can investigate that first?

**Comment by veri-tty** [comment]
![swappy-20241008_160610](https://github.com/user-attachments/assets/0a5a61ff-f891-4d06-9d9d-fe750cc8f811)
thanks for the quick response :)
colors.conf  and colors_wal.conf are there , both contain 2 lines only however. i assumed that the picking of wallpaper via the AGS menu would create/ populate these files, guess i  shouldeve checked on that first

**Comment by 0thElement** [comment]
AGS calls wpg, which in turns has been configured to generate the colors.conf (and other configuration for other apps) which is read by hyprland. Good luck! :)

**Comment by veri-tty** [comment]
ok, ill try and work it out from here, thanks :)
